// ============================================================
// Application strings — single source of truth for all UI text
// ============================================================

export const strings = {

  // ── Common / Shared ────────────────────────────────────────
  common: {
    save:           "Save changes",
    saving:         "Saving...",
    cancel:         "Cancel",
    back:           "Back",
    home:           "Home",
    edit:           "Edit",
    all:            "All",
    loading:        "Loading...",
    empty:          "No results found.",
    logout:         "Logout",
    signIn:         "Sign in",
    signUp:         "Sign up",
    poweredBy:      "Powered by",
    noData:         "—",
  },

  // ── Navigation ─────────────────────────────────────────────
  nav: {
    brand:          "Vacaciones Digital Team",
  },

  // ── Auth ───────────────────────────────────────────────────
  auth: {
    login: {
      title:              "Login",
      description:        "Enter your email below to login to your account",
      emailLabel:         "Email",
      emailPlaceholder:   "m@example.com",
      passwordLabel:      "Password",
      forgotPassword:     "Forgot your password?",
      submitIdle:         "Login",
      submitLoading:      "Logging in...",
      noAccount:          "Don't have an account?",
      signUpLink:         "Sign up",
    },
    signUp: {
      title:              "Sign up",
      description:        "Create a new account",
      fullNameLabel:      "Full name",
      fullNamePlaceholder:"Jane Doe",
      emailLabel:         "Email",
      emailPlaceholder:   "m@example.com",
      officeLabel:        "Office",
      categoryLabel:      "Category",
      companyLabel:       "Company",
      companyRequired:    "Please select a company.",
      passwordLabel:      "Password",
      repeatPasswordLabel:"Repeat Password",
      submitIdle:         "Sign up",
      submitLoading:      "Creating an account...",
      hasAccount:         "Already have an account?",
      loginLink:          "Login",
      errorDomain:        "Only corporate email from our company are allowed.",
      errorPasswordMatch: "Passwords do not match",
      errorCompany:       "Please select a company for external employees.",
      errorGeneric:       "An error occurred",
    },
    forgotPassword: {
      title:              "Reset Your Password",
      description:        "Type in your email and we'll send you a link to reset your password",
      emailLabel:         "Email",
      emailPlaceholder:   "m@example.com",
      submitIdle:         "Send reset email",
      submitLoading:      "Sending...",
      hasAccount:         "Already have an account?",
      loginLink:          "Login",
      successTitle:       "Check Your Email",
      successDescription: "Password reset instructions sent",
      successBody:        "If you registered using your email and password, you will receive a password reset email.",
    },
    updatePassword: {
      title:              "Reset Your Password",
      description:        "Please enter your new password below.",
      newPasswordLabel:   "New password",
      newPasswordPlaceholder: "New password",
      submitIdle:         "Save new password",
      submitLoading:      "Saving...",
    },
    signUpSuccess: {
      title:       "Thank you for signing up!",
      description: "Check your email to confirm",
      body:        "You've successfully signed up. Please check your email to confirm your account before signing in.",
    },
    error: {
      title:       "Sorry, something went wrong.",
      codePrefix:  "Code error: ",
      fallback:    "An unspecified error occurred.",
    },
  },

  // ── Dashboard (main page) ──────────────────────────────────
  dashboard: {
    greeting:               (name: string) => `Welcome back, ${name} 👋`,
    subtitle:               "What would you like to manage today?",
    vacationSectionTitle:   (year: number) => `My vacations · ${year}`,
    statDaysTaken:          "Days taken",
    statPending:            "Pending approval",
    statRemaining:          (total: number) => `Remaining of ${total}`,
    cardProjects:           "Projects",
    cardProjectsDesc:       "View and manage all engagement projects, their dates and assigned team members.",
    cardProjectsLink:       "Go to Projects →",
    cardEmployees:          "Employees",
    cardEmployeesDesc:      "View the full employee list and edit their details, office and role.",
    cardEmployeesLink:      "Go to Employees →",
    cardRequests:           "Vacation requests",
    cardRequestsDesc:       "Review, approve or reject team vacation requests and notify employees by email.",
    cardRequestsLink:       "Go to Requests →",
    cardVacations:          "Vacations",
    cardVacationsDesc:      "Request vacation days, track your balance and review the status of your requests.",
    cardVacationsLink:      "Go to Vacations →",
    cardOverview:           "Vacation overview",
    cardOverviewDesc:       "Monthly calendar view of the whole team's vacations, filterable by project.",
    cardOverviewLink:       "Go to Overview →",
  },

  // ── Employees ──────────────────────────────────────────────
  employees: {
    listTitle:            "Employees",
    listCount:            (n: number) => `${n} employee${n !== 1 ? "s" : ""} registered`,
    colName:              "Name",
    colEmail:             "Email",
    colOffice:            "Office",
    colRole:              "Role",
    colJoined:            "Joined",
    empty:                "No employees found.",
    editTitle:            "Edit employee",
    editSubtitle:         (name: string) => `Update details for ${name}.`,
    formNameLabel:        "Full name",
    formEmailLabel:       "Email",
    formEmailReadOnly:    "Email is managed by the authentication system and cannot be changed here.",
    formOfficeLabel:      "Office",
    formRoleLabel:        "Role",
    formCategoryLabel:    "Category",
    formCompanyLabel:     "Company",
  },

  // ── Projects ───────────────────────────────────────────────
  projects: {
    listTitle:            "Projects",
    listCount:            (n: number) => `${n} project${n !== 1 ? "s" : ""} registered`,
    newButton:            "New project",
    colId:                "ID Engagement",
    colName:              "Name",
    colStart:             "Start date",
    colEnd:               "End date",
    colStatus:            "Status",
    colEmployees:         "Employees",
    badgeActive:          "Active",
    badgeFinished:        "Finished",
    employeeCount:        (n: number) => `${n} employee${n !== 1 ? "s" : ""}`,
    errorLoading:         (msg: string) => `Error loading projects: ${msg}`,
    newTitle:             "New project",
    newSubtitle:          "Fill in the details and assign team members.",
    editTitle:            "Edit project",
    editSubtitle:         (name: string) => `Update the details for ${name}.`,
    formIconLabel:        "Project icon",
    formIconHint:         "Click the circle to upload an image. Will be displayed rounded.",
    formIconChoose:       "Choose image",
    formIconAlt:          "Icon preview",
    formIconUploadTitle:  "Upload icon",
    formColorLabel:       "Project color",
    formColorSelected:    "Selected:",
    formIdLabel:          "ID Engagement",
    formIdPlaceholder:    "ENG-001",
    formIdHint:           "The engagement ID cannot be changed after creation.",
    formNameLabel:        "Project name",
    formNamePlaceholder:  "Project name",
    formStartLabel:       "Start date",
    formEndLabel:         "End date",
    formEmployeesLabel:   "Assign employees",
    formEmployeesEmpty:   "No employees found.",
    formEmployeesCount:   (n: number) => `${n} employee${n !== 1 ? "s" : ""} selected`,
    submitCreate:         "Create project",
    submitCreating:       "Creating...",
    emptyState:           "No projects yet.",
    emptyCreate:          "Create your first project",
  },

  // ── Vacations ──────────────────────────────────────────────
  vacations: {
    pageTitle:            "Vacations",
    noProfile:            "Your employee profile has not been set up yet. Please contact an administrator.",
    myVacationsTitle:     "My vacations",
    greeting:             (name: string) => `Hi, ${name}. Select your vacation days below.`,
    teamOverviewLink:     "Team overview",

    calendarOfficeLabel:  "Office:",
    calendarOfficeHint:   "Holidays shown are specific to your office.",
    calendarDaysShort:    ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"] as string[],
    calendarMonths:       ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"] as string[],
    calendarTitleApproved:   "Approved",
    calendarTitlePending:    "Pending approval",
    calendarTitleRejected:   "Rejected",
    calendarTitleHoliday:    "Public holiday",
    calendarTitleWeekend:    "Weekend",
    legendSelected:       "Selected",
    legendRange:          "Range",
    legendApproved:       "Approved",
    legendPending:        "Pending",
    legendRejected:       "Rejected",
    legendHoliday:        "Public holiday",
    legendWeekend:        "Weekend",

    selectionTitle:       "Selection",
    selectionFrom:        "From: ",
    selectionTo:          "To: ",
    selectionWorkingDays: "Working days: ",
    selectionRemaining:   "Remaining balance: ",
    errorNotEnoughDays:   "You don't have enough vacation days for this selection.",
    errorOverlapInline:   "Your selection overlaps with an existing vacation request.",
    errorOverlapSubmit:   "Your selection overlaps with an existing vacation request. Please choose different dates.",
    submitIdle:           "Request vacation",
    submitLoading:        "Submitting...",
    clearButton:          "Clear",
    successMessage:       (n: number) => `Request for ${n} day${n !== 1 ? "s" : ""} submitted successfully.`,

    statSolicitados:      "Solicitados",
    statAprobados:        "Aprobados",
    statPendientes:       "Pendientes",
    statDisfrutados:      "Disfrutados",
    statRestantes:        "Restantes",
    statOf:               (max: number) => `de ${max} días`,

    requestsTitle:        "My vacation requests",
    requestsEmpty:        "No vacation requests yet.",
    requestsLegendPending:   "Pending approval",
    requestsLegendApproved:  "Approved",
    requestsLegendRejected:  "Rejected",
    requestsLegendCancelled: "Cancelled",
    colFrom:              "From",
    colTo:                "To",
    colDays:              "Days",
    colYear:              "Year",
    colStatus:            "Status",
    statusPending:        "Pending",
    statusApproved:       "Approved",
    statusRejected:       "Rejected",
    statusCancelled:      "Cancelled",

    overviewTitle:        "Vacation overview",
    overviewSubtitleAdmin:"Monthly view of all employees' vacation requests.",
    overviewSubtitleUser: "Monthly view of your project team's vacation requests.",
    overviewFilterLabel:  "Filter by project:",
    overviewFilterAll:    "All employees",
    overviewFilterShowing:(n: number, project: string) => `Showing ${n} employee${n !== 1 ? "s" : ""} assigned to ${project}`,
    overviewColEmployee:  "Employee",
    overviewColOffice:    "Office",
    overviewEmpty:        "No employees to display.",
  },

  // ── Admin ──────────────────────────────────────────────────
  admin: {
    requestsTitle:        "Vacation requests",
    requestsCountPending: (n: number) => `${n} request${n !== 1 ? "s" : ""} pending approval.`,
    requestsAllReviewed:  "All requests have been reviewed.",
    requestsError:        (msg: string) => `Error loading requests: ${msg}`,
    requestsMigrationHint:"Make sure migrations 000006, 000007 and 000008 have been applied in Supabase.",

    filterAll:            "All",
    filterPending:        "Pending",
    filterApproved:       "Approved",
    filterRejected:       "Rejected",
    searchPlaceholder:    "Search by employee name…",
    projectFilterLabel:   "Project:",
    tableEmpty:           "No requests match the current filters.",

    colEmployee:          "Employee",
    colProject:           "Project",
    colFrom:              "From",
    colTo:                "To",
    colDays:              "Days",
    colRequested:         "Requested",
    colStatus:            "Status",
    colActions:           "Actions",

    statusPending:        "Pending",
    statusApproved:       "Approved",
    statusRejected:       "Rejected",
    statusCancelled:      "Cancelled",

    approveButton:        "Approve",
    rejectButton:         "Reject",
    rejectCancelButton:   "Cancel",
    rejectPlaceholder:    "Rejection reason (optional)…",
    confirmRejectButton:  "Confirm reject",
  },

} as const;
