// ============================================================
// Application strings — single source of truth for all UI text
// ============================================================

export const strings = {

  // ── Common / Shared ────────────────────────────────────────
  common: {
    save:           "Save changes",
    saving:         "Saving...",
    cancel:         "Cancel",
    back:           "Back",
    home:           "Home",
    edit:           "Edit",
    all:            "All",
    loading:        "Loading...",
    empty:          "No results found.",
    logout:         "Logout",
    signIn:         "Sign in",
    signUp:         "Sign up",
    poweredBy:      "Powered by",
    noData:         "—",
  },

  // ── Navigation ─────────────────────────────────────────────
  nav: {
    brand:          "Vacaciones Digital Team",
  },

  // ── Auth ───────────────────────────────────────────────────
  auth: {
    login: {
      title:              "Login",
      description:        "Enter your email below to login to your account",
      emailLabel:         "Email",
      emailPlaceholder:   "m@example.com",
      passwordLabel:      "Password",
      forgotPassword:     "Forgot your password?",
      submitIdle:         "Login",
      submitLoading:      "Logging in...",
      noAccount:          "Don't have an account?",
      signUpLink:         "Sign up",
    },
    signUp: {
      title:              "Sign up",
      description:        "Create a new account",
      fullNameLabel:      "Full name",
      fullNamePlaceholder:"Jane Doe",
      emailLabel:         "Email",
      emailPlaceholder:   "m@example.com",
      officeLabel:        "Office",
      categoryLabel:      "Category",
      companyLabel:       "Company",
      companyRequired:    "Please select a company.",
      passwordLabel:      "Password",
      repeatPasswordLabel:"Repeat Password",
      submitIdle:         "Sign up",
      submitLoading:      "Creating an account...",
      hasAccount:         "Already have an account?",
      loginLink:          "Login",
      errorDomain:        "Only corporate email from our company are allowed.",
      errorPasswordMatch: "Passwords do not match",
      errorCompany:       "Please select a company for external employees.",
      errorGeneric:       "An error occurred",
    },
    forgotPassword: {
      title:              "Reset Your Password",
      description:        "Type in your email and we'll send you a link to reset your password",
      emailLabel:         "Email",
      emailPlaceholder:   "m@example.com",
      submitIdle:         "Send reset email",
      submitLoading:      "Sending...",
      hasAccount:         "Already have an account?",
      loginLink:          "Login",
      successTitle:       "Check Your Email",
      successDescription: "Password reset instructions sent",
      successBody:        "If you registered using your email and password, you will receive a password reset email.",
    },
    updatePassword: {
      title:              "Reset Your Password",
      description:        "Please enter your new password below.",
      newPasswordLabel:   "New password",
      newPasswordPlaceholder: "New password",
      submitIdle:         "Save new password",
      submitLoading:      "Saving...",
    },
    signUpSuccess: {
      title:       "Thank you for signing up!",
      description: "Check your email to confirm",
      body:        "You've successfully signed up. Please check your email to confirm your account. Once verified, an administrator will review and approve your access before you can sign in.",
    },
    pendingApproval: {
      title:       "Account pending approval",
      description: "An administrator must approve your account",
      body:        "Your account has been created and your email has been verified. An administrator will review and approve your access shortly. You will be able to sign in once your account is approved.",
    },
    error: {
      title:       "Sorry, something went wrong.",
      codePrefix:  "Code error: ",
      fallback:    "An unspecified error occurred.",
    },
  },

  // ── Dashboard (main page) ──────────────────────────────────
  dashboard: {
    greeting:               (name: string) => `Welcome back, ${name} 👋`,
    subtitle:               "What would you like to manage today?",
    vacationSectionTitle:   (year: number) => `My vacations · ${year}`,
    statDaysTaken:          "Days taken",
    statPending:            "Pending approval",
    statRemaining:          (total: number) => `Remaining of ${total}`,
    cardProjects:           "Clientes",
    cardProjectsDesc:       "Gestiona los clientes, sus fechas y los miembros asignados.",
    cardProjectsLink:       "Ir a Clientes →",
    cardEmployees:          "Employees",
    cardEmployeesDesc:      "View the full employee list and edit their details, office and role.",
    cardEmployeesLink:      "Go to Employees →",
    adminBadge:             "Admin",
    cardRequests:           "Vacation requests",
    cardRequestsDesc:       "Review, approve or reject team vacation requests and notify employees by email.",
    cardRequestsLink:       "Go to Requests →",
    cardVacations:          "Vacations",
    cardVacationsDesc:      "Request vacation days, track your balance and review the status of your requests.",
    cardVacationsLink:      "Go to Vacations →",
    cardOverview:           "Vacation overview",
    cardOverviewDesc:       "Monthly calendar view of the whole team's vacations, filterable by client.",
    cardOverviewLink:       "Go to Overview →",
    cardTeamOverview:       "Team vacations",
    cardTeamOverviewDesc:   "Calendar view of your client colleagues' vacations.",
  },

  // ── Employees ──────────────────────────────────────────────
  employees: {
    listTitle:            "Employees",
    listCount:            (n: number) => `${n} employee${n !== 1 ? "s" : ""} registered`,
    colName:              "Name",
    colEmail:             "Email",
    colOffice:            "Office",
    colRole:              "Role",
    colJoined:            "Joined",
    empty:                "No employees found.",
    editTitle:            "Edit employee",
    editSubtitle:         (name: string) => `Update details for ${name}.`,
    formNameLabel:        "Full name",
    formEmailLabel:       "Email",
    formEmailReadOnly:    "Email is managed by the authentication system and cannot be changed here.",
    formOfficeLabel:      "Office",
    formRoleLabel:        "Role",
    formCategoryLabel:    "Category",
    formCompanyLabel:     "Company",
    formCostPerHourLabel: "Coste por hora (€)",
    formCostPerHourHint:  "Coste base que se cargará automáticamente al asignar este empleado a una oportunidad.",
    formWeeklyHoursLabel: "Horas semanales Minor",
    formWeeklyHoursHint:  "Número de horas que este empleado debe imputar semanalmente en el proyecto Minor.",
    formExitDateLabel:    "Fecha de baja",
    formExitDateHint:     "Si el empleado ha abandonado la empresa, indica la fecha de salida. A partir de esa fecha quedará excluido de reports, estadísticas, skills, Copilot y no podrá imputar horas en Minor.",
    formExitDateClear:    "Reactivar empleado",
    badgeBaja:            "Baja",
    colExitDate:          "Fecha baja",
    inactiveMessage:      "Tu cuenta está marcada como baja. Si crees que es un error, contacta con un administrador.",
  },

  // ── GitHub Copilot ────────────────────────────────────────
  copilot: {
    pageTitle:               "Licencia GitHub Copilot",
    pageSubtitle:            "Indica si tienes licencia, el engagement de solicitud y los proyectos en los que la usarás.",
    optionYes:               "Sí",
    optionNo:                "No",
    formLicenseLabel:        "¿Tienes licencia de GitHub Copilot?",
    formEngagementLabel:     "Engagement para la licencia",
    formEngagementPlaceholder: "Ej. ENG-1234 - Proyecto X",
    formEngagementRequired:  "Debes indicar el engagement donde se solicitó la licencia.",
    formClientsLabel:        "Proyectos donde usarás Copilot (próximos meses)",
    formClientsHint:         "Puedes seleccionar uno o varios clientes.",
    formClientsRequired:     "Selecciona al menos un proyecto para usar Copilot.",
    noClientsAvailable:      "No hay proyectos disponibles todavía. Contacta con un administrador.",
    saved:                   "Datos de licencia guardados correctamente.",
    dashboardCard:           "GitHub Copilot",
    dashboardCardDesc:       "Informa si tienes licencia y en qué clientes la usarás en los próximos meses.",
    dashboardCardLink:       "Ir a Copilot →",
    managerPageTitle:        "Resumen de licencias Copilot",
    managerPageSubtitle:     "Consulta por proyecto la información de licencia reportada por cada empleado.",
    managerDashboardCard:    "Resumen Copilot",
    managerDashboardCardDesc:"Revisa por proyecto qué empleados tienen licencia y el engagement informado.",
    managerDashboardCardLink:"Ver resumen Copilot →",
    managerFilterLicenseLabel: "Filtro de licencia",
    managerFilterLicenseAll:   "Todos",
    managerFilterLicenseWith:  "Con licencia",
    managerFilterLicenseWithout: "Sin licencia",
    managerSortByLabel:        "Ordenar por",
    managerSortByEmployee:     "Empleado",
    managerSortByEngagement:   "Engagement informado",
    managerSortDirectionLabel: "Dirección",
    managerSortDirectionAsc:   "Ascendente",
    managerSortDirectionDesc:  "Descendente",
    managerColEmployee:        "Empleado",
    managerColHasLicense:      "Licencia Copilot",
    managerColEngagement:      "Engagement informado",
    managerEmpty:              "No hay datos para mostrar con los filtros actuales.",
    managerProjectCount:       (n: number) => `${n} empleado${n !== 1 ? "s" : ""}`,
  },

  // ── Projects (Clientes) ───────────────────────────────────
  projects: {
    listTitle:            "Clientes",
    listCount:            (n: number) => `${n} cliente${n !== 1 ? "s" : ""} registrado${n !== 1 ? "s" : ""}`,
    newButton:            "Nuevo cliente",
    colId:                "ID Engagement",
    colName:              "Nombre",
    colStart:             "Fecha inicio",
    colEnd:               "Fecha fin",
    colStatus:            "Estado",
    colEmployees:         "Empleados",
    badgeActive:          "Activo",
    badgeFinished:        "Finalizado",
    employeeCount:        (n: number) => `${n} employee${n !== 1 ? "s" : ""}`,
    errorLoading:         (msg: string) => `Error cargando clientes: ${msg}`,
    newTitle:             "Nuevo cliente",
    newSubtitle:          "Rellena los datos y asigna los miembros del equipo.",
    editTitle:            "Editar cliente",
    editSubtitle:         (name: string) => `Actualiza los datos de ${name}.`,
    formIconLabel:        "Icono del cliente",
    formIconHint:         "Haz clic en el círculo para subir una imagen. Se mostrará redondeada.",
    formIconChoose:       "Elegir imagen",
    formIconAlt:          "Vista previa del icono",
    formIconUploadTitle:  "Subir icono",
    formColorLabel:       "Color del cliente",
    formColorSelected:    "Seleccionado:",
    formIdLabel:          "ID Engagement",
    formIdPlaceholder:    "ENG-001",
    formIdHint:           "El ID de engagement no se puede cambiar después de la creación.",
    formNameLabel:        "Nombre del cliente",
    formNamePlaceholder:  "Nombre del cliente",
    formStartLabel:       "Fecha de inicio",
    formEndLabel:         "Fecha de fin",
    formEmployeesLabel:   "Asignar empleados",
    formEmployeesEmpty:   "No se encontraron empleados.",
    formEmployeesSearch:  "Buscar empleados…",
    formEmployeesCount:   (n: number) => `${n} empleado${n !== 1 ? "s" : ""} seleccionado${n !== 1 ? "s" : ""}`,
    formIsMinorLabel:     "Cliente Minor",
    formIsMinorHint:      "Marca esta opción para habilitar la sección de imputación de horas Minor en este cliente.",
    submitCreate:         "Crear cliente",
    submitCreating:       "Creando...",
    emptyState:           "No hay clientes todavía.",
    emptyCreate:          "Crea tu primer cliente",
  },

  // ── Vacations ──────────────────────────────────────────────
  vacations: {
    pageTitle:            "Vacations",
    noProfile:            "Your employee profile has not been set up yet. Please contact an administrator.",
    myVacationsTitle:     "My vacations",
    greeting:             (name: string) => `Hi, ${name}. Select your vacation days below.`,
    teamOverviewLink:     "Team overview",

    calendarOfficeLabel:  "Office:",
    calendarOfficeHint:   "Holidays shown are specific to your office.",
    calendarDaysShort:    ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"] as string[],
    calendarMonths:       ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"] as string[],
    calendarTitleApproved:   "Approved",
    calendarTitlePending:    "Pending approval",
    calendarTitleRejected:   "Rejected",
    calendarTitleHoliday:    "Public holiday",
    calendarTitleWeekend:    "Weekend",
    legendSelected:       "Selected",
    legendRange:          "Range",
    legendApproved:       "Approved",
    legendPending:        "Pending",
    legendRejected:       "Rejected",
    legendHoliday:        "Public holiday",
    legendWeekend:        "Weekend",
    legendBootcampApproved: "Bootcamp aprobado",
    legendBootcampPending:  "Bootcamp pendiente",
    legendMedicalLeaveApproved: "Baja médica aprobada",

    selectionTitle:       "Selection",
    selectionFrom:        "From: ",
    selectionTo:          "To: ",
    selectionWorkingDays: "Working days: ",
    selectionRemaining:   "Remaining balance: ",
    errorNotEnoughDays:   "You don't have enough vacation days for this selection.",
    errorOverlapInline:   "Your selection overlaps with an existing vacation request.",
    errorOverlapSubmit:   "Your selection overlaps with an existing vacation request. Please choose different dates.",
    submitIdle:           "Request vacation",
    submitLoading:        "Submitting...",
    clearButton:          "Clear",
    successMessage:       (n: number) => `Request for ${n} day${n !== 1 ? "s" : ""} submitted successfully.`,

    bootcampCheckbox:     "Días de Bootcamp",
    bootcampHint:         "Los días de Bootcamp no se descuentan del saldo de vacaciones (máx. 2 días/año).",
    bootcampRemaining:    "Días Bootcamp restantes: ",
    bootcampCalendarTitleApproved: "Bootcamp aprobado",
    bootcampCalendarTitlePending:  "Bootcamp pendiente",
    medicalLeaveCheckbox: "Días de baja médica",
    medicalLeaveHint:     "Los días de baja médica no se descuentan del saldo de vacaciones y se aprueban automáticamente.",
    medicalLeaveCalendarTitleApproved: "Baja médica aprobada",
    medicalLeaveAutoApproveLabel: "Estado: ",
    medicalLeaveAutoApproveValue: "Aprobación automática",
    badgeMedicalLeave:    "Baja médica",

    statSolicitados:      "Solicitados",
    statAprobados:        "Aprobados",
    statPendientes:       "Pendientes",
    statDisfrutados:      "Disfrutados",
    statRestantes:        "Restantes",
    statOf:               (max: number) => `de ${max} días`,

    requestsTitle:        "My vacation requests",
    requestsEmpty:        "No vacation requests yet.",
    requestsLegendPending:   "Pending approval",
    requestsLegendApproved:  "Approved",
    requestsLegendRejected:  "Rejected",
    requestsLegendCancelled: "Cancelled",
    colFrom:              "From",
    colTo:                "To",
    colDays:              "Days",
    colYear:              "Year",
    colStatus:            "Status",
    cancelButton:         "Cancel request",
    cancelConfirm:        "Are you sure you want to cancel this vacation request?",
    statusPending:        "Pending",
    statusApproved:       "Approved",
    statusRejected:       "Rejected",
    statusCancelled:      "Cancelled",

    overviewTitle:        "Vacation overview",
    overviewSubtitleAdmin:"Monthly view of all employees' vacation requests.",
    overviewSubtitleUser: "Monthly view of your client team's vacation requests.",

    teamTitle:            "Team vacations",
    teamSubtitle:         "Vacation overview for colleagues assigned to your clients.",
    teamNoProjects:       "You are not assigned to any clients. Contact an admin to be added to a client.",
    overviewFilterLabel:  "Filter by client:",
    overviewFilterAll:    "All employees",
    overviewFilterShowing:(n: number, project: string) => `Showing ${n} employee${n !== 1 ? "s" : ""} assigned to ${project}`,
    overviewColEmployee:  "Employee",
    overviewColOffice:    "Office",
    overviewColCategory:  "Category",
    overviewColSpecs:     "Specializations",
    overviewFilterCategory: "Filter by category:",
    overviewFilterSpec:     "Filter by specialization:",
    overviewFilterAllCategories: "All categories",
    overviewFilterAllSpecs:      "All specializations",
    overviewEmpty:        "No employees to display.",

    availabilityLink:          "Disponibilidad",
    availabilityTitle:         "Disponibilidad del equipo",
    availabilitySubtitle:      "Días laborables disponibles por semana hasta fin de año. Descuenta vacaciones aprobadas, festivos, bootcamp y bajas médicas.",
    availabilityTotalRow:      "Total",
    availabilityLegendFull:    "Alta (≥80%)",
    availabilityLegendPartial: "Media (40–79%)",
    availabilityLegendLow:     "Baja (<40%)",
    availabilityLegendNone:    "Sin disponibilidad",
    availabilityLegendHoliday: "Sin días laborables",
    availabilityColEmployee:   "Empleado",
    availabilityColCategory:   "Categoría",
    availabilityColSpecs:      "Especializaciones",
    availabilityColCount:      "Empleados",
    availabilityGroupByLabel:  "Agrupar por:",
    availabilityGroupEmployee: "Empleado",
    availabilityGroupProject:  "Cliente",
    availabilityGroupTeam:     "Equipo",
    availabilityGroupCategory: "Categoría",
    availabilityGroupSpec:     "Especialización",
  },

  // ── Admin ──────────────────────────────────────────────────
  admin: {
    approvalsTitle:       "Pending account approvals",
    approvalsSubtitle:    "Review and approve new employee accounts before they can access the application.",
    requestsTitle:        "Vacation requests",
    requestsCountPending: (n: number) => `${n} request${n !== 1 ? "s" : ""} pending approval.`,
    requestsAllReviewed:  "All requests have been reviewed.",
    requestsError:        (msg: string) => `Error loading requests: ${msg}`,
    requestsMigrationHint:"Make sure migrations 000006, 000007 and 000008 have been applied in Supabase.",

    filterAll:            "All",
    filterPending:        "Pending",
    filterApproved:       "Approved",
    filterRejected:       "Rejected",
    searchPlaceholder:    "Search by employee name…",
    projectFilterLabel:   "Cliente:",
    tableEmpty:           "No requests match the current filters.",

    colEmployee:          "Employee",
    colProject:           "Cliente",
    colFrom:              "From",
    colTo:                "To",
    colDays:              "Days",
    colRequested:         "Requested",
    colStatus:            "Status",
    colActions:           "Actions",
    badgeBootcamp:        "Bootcamp",
    badgeMedicalLeave:    "Baja médica",

    statusPending:        "Pending",
    statusApproved:       "Approved",
    statusRejected:       "Rejected",
    statusCancelled:      "Cancelled",

    approveButton:        "Approve",
    rejectButton:         "Reject",
    cancelButton:         "Cancel approval",
    rejectCancelButton:   "Cancel",
    rejectPlaceholder:    "Rejection reason (optional)…",
    confirmRejectButton:  "Confirm reject",

    // Vacation settings
    vacationSettings: {
      pageTitle:            "Configuración de vacaciones",
      pageSubtitle:         "Configura los días de vacaciones y las horas semanales de imputación por categoría.",
      daysSuffix:           "días / año",
      saveSuccess:          "Configuración guardada correctamente.",
      vacationDaysSection:  "Días de vacaciones por categoría",
      hoursSection:         "Horas semanales de imputación por categoría",
      hoursSectionDesc:     "Valores por defecto al asignar empleados a engagements. En jornada de verano (16 jul – 15 sep) se usan las horas de verano.",
      categoryCol:          "Categoría",
      regularHoursCol:      "Horas/sem (regular)",
      summerHoursCol:       "Horas/sem (verano)",
      dashboardCard:        "Vacation settings",
      dashboardCardDesc:    "Configure the number of vacation days available per category.",
      dashboardCardLink:    "Go to Settings →",
    },

    // Holidays management
    holidays: {
      pageTitle:            "Festivos",
      pageSubtitle:         "Gestiona los festivos nacionales y por centro de trabajo.",
      dashboardCard:        "Festivos",
      dashboardCardDesc:    "Gestiona los festivos nacionales y por centro de trabajo.",
      dashboardCardLink:    "Gestionar →",
    },
  },

  // ── Skills ─────────────────────────────────────────────────
  skills: {
    pageTitle:            "My skills",
    pageSubtitle:         "Add keywords that describe your professional knowledge and expertise.",
    inputPlaceholder:     "Add a skill (e.g. TypeScript, Power BI…)",
    inputAriaLabel:       "New skill name",
    addButton:            "Add",
    noSkills:             "No skills in the pool yet. Be the first to add one!",
    allSkillsLabel:       "All skills",
    allSkillsHint:        "Click a skill to add or remove it. Use the level buttons [0][1][2][3] to set your expertise.",
    mySkillsLabel:        "My skills",
    skillAlreadyAdded:    "You have already added this skill.",
    noMatchCreate:        "No skills match your search. Press Enter or click Add to create it.",
    errorLoading:         "Error loading skills. Please try again.",
    errorAdding:          (msg: string) => `Could not add skill: ${msg}`,
    errorRemoving:        (msg: string) => `Could not remove skill: ${msg}`,

    // Expertise levels
    level0:               "Sin conocimiento",
    level1:               "Necesita supervisión",
    level2:               "Autónomo",
    level3:               "Puede liderar",

    // Specializations
    specializationsLabel:             "Specializations",
    specializationsSubtitle:          "Select your areas of specialization. Click to add or remove.",
    specializationsInputPlaceholder:  "Add a specialization (e.g. Frontend, Data Analytics…)",
    specializationsHint:              "Click a specialization to add or remove it. Type to search or create a new one.",
    specializationsEmpty:             "No specializations in the pool yet. Be the first to add one!",
    searchColSpecializations:         "Specializations",
    dashboardCard:        "Skills",
    dashboardCardDesc:    "Register your professional knowledge and expertise as searchable keywords.",
    dashboardCardLink:    "Go to Skills →",

    // Admin — manage skills catalogue
    adminPageTitle:      "Gestión de skills",
    adminPageSubtitle:   "Añade o elimina skills por categoría. Los empleados podrán seleccionarlas desde su perfil.",
    adminAddPlaceholder: (cat: string) => `Nueva skill en ${cat}…`,
    adminAddButton:      "Añadir",
    adminNoSkills:       (cat: string) => `No hay skills en ${cat}. Añade la primera.`,
    adminDeleteTitle:    "Eliminar skill",
    adminDashboardLink:  "Gestionar skills →",
    adminAddCategory:    "Nueva categoría",
    adminNewCategoryPlaceholder: "Nombre de la categoría…",
    addSkillTitle:       "Add skill",
    removeSkillTitle:    "Remove skill",

    // Admin — search employees by skill
    searchPageTitle:      "Search by skills",
    searchPageSubtitle:   "Find employees by one or more skills. Select skills below to filter the results.",
    searchNoSkillsPool:   "No skills have been registered yet.",
    searchFilterLabel:    "Filter by skills",
    searchFilterHint:     "Click skills to filter. Multiple selections act as AND (employee must have all).",
    searchMinLevelLabel:  "Minimum level:",
    searchMinLevelAny:    "Any",
    searchClearFilters:   "Clear filters",
    searchResultsCount:   (n: number) => `${n} employee${n !== 1 ? "s" : ""} found`,
    searchNoResults:      "No employees match the selected skills.",
    searchNoFilters:      "Select one or more skills above to start searching.",
    searchColEmployee:    "Employee",
    searchColCategory:    "Category",
    searchColProjects:    "Active clients",
    searchColSkills:      "Skills",
    searchNoProjects:     "—",
    searchExportCsv:      "Download Excel",

    // Admin dashboard card
    searchDashboardCard:     "Search by skills",
    searchDashboardCardDesc: "Find employees by their registered skills and see their category and active clients.",
    searchDashboardCardLink: "Go to Skills search →",
  },

  // ── Minor ─────────────────────────────────────────────────
  minor: {
    // Employee hours page
    pageTitle:              "Horas Minor",
    pageSubtitle:           "Registra las horas semanales que has trabajado en cada subproyecto de Minor.",
    weeklyHoursTarget:      (h: number) => `Objetivo semanal: ${h} h`,
    weekLabel:              (start: string, end: string) => `${start} – ${end}`,
    totalLabel:             "Total",
    saveWeekButton:         "Guardar semana",
    savingButton:           "Guardando...",
    savedMessage:           "Guardado",
    errorSaving:            (msg: string) => `Error al guardar: ${msg}`,
    noSubprojects:          "No hay subproyectos configurados. Contacta con un administrador de Minor.",
    notMinorMember:         "No estás asignado al proyecto Minor.",
    prevMonth:              "Mes anterior",
    nextMonth:              "Mes siguiente",
    prevWeek:               "Semana anterior",
    nextWeek:               "Semana siguiente",
    // Admin subprojects page
    adminSubprojectsTitle:  "Subproyectos Minor",
    adminSubprojectsSubtitle: "Gestiona la lista de subproyectos disponibles para imputar horas.",
    addSubprojectButton:    "Añadir subproyecto",
    addSubprojectPlaceholder: "Nombre del subproyecto…",
    editSubprojectTitle:    "Editar subproyecto",
    subprojectNameLabel:    "Nombre",
    subprojectActiveLabel:  "Activo",
    subprojectSaveButton:   "Guardar",
    subprojectSavingButton: "Guardando...",
    subprojectDeleteButton: "Eliminar",
    subprojectDeleteConfirm: "¿Eliminar este subproyecto? Las horas imputadas asociadas también se eliminarán.",
    subprojectEmpty:        "No hay subproyectos todavía.",
    subprojectColName:      "Nombre",
    subprojectColStatus:    "Estado",
    subprojectColActions:   "Acciones",
    subprojectActive:       "Activo",
    subprojectInactive:     "Inactivo",
    notMinorAdmin:          "No tienes permisos de administrador en el proyecto Minor.",
    employeeInactive:       "Tu cuenta está marcada como baja. Si crees que es un error, contacta con un administrador.",
    adminHoursBadgeBaja:    "Baja",
    // Admin hours view
    adminHoursTitle:        "Horas imputadas – Minor",
    adminHoursSubtitle:     "Resumen semanal de horas imputadas por empleado y subproyecto.",
    adminHoursPrevWeek:     "Semana anterior",
    adminHoursNextWeek:     "Semana siguiente",
    adminHoursWeekOf:       (date: string) => `Semana del ${date}`,
    adminHoursColEmployee:  "Empleado",
    adminHoursColTotal:     "Total",
    adminHoursNoEmployees:  "No hay empleados asignados al proyecto Minor.",
    adminHoursSlackButton:  "Notificar empleados incompletos",
    adminHoursSlackSending: "Enviando…",
    adminHoursSlackSent:    "Notificación enviada",
    adminHoursSlackError:   "Error al enviar la notificación",
    adminHoursAllComplete:  "Todos los empleados han completado sus horas esta semana.",
    // Admin monthly summary view
    adminMonthlyTitle:      "Resumen mensual Minor",
    adminMonthlySubtitle:   "Vista anual con una columna por mes y total de horas por subproyecto, sumando a todos los empleados participantes.",
    adminMonthlyPrevMonth:  "Año anterior",
    adminMonthlyNextMonth:  "Año siguiente",
    adminMonthlyMonthOf:    (year: string) => `Año: ${year}`,
    adminMonthlyColSubproject: "Subproyecto",
    adminMonthlyColEmployees:  "Empleados",
    adminMonthlyQuarterLabel:  (quarter: number) => `T${quarter}`,
    adminMonthlyColTotalHours: "Horas totales",
    adminMonthlyNoData:     "No hay horas imputadas para este mes.",
    // Dashboard cards
    dashboardCard:          "Imputar horas Minor",
    dashboardCardDesc:      "Registra las horas semanales trabajadas en los subproyectos de Minor.",
    dashboardCardLink:      "Ir a Minor →",
    adminDashboardCard:     "Administración Minor",
    adminDashboardCardDesc: "Gestiona subproyectos y revisa las horas imputadas por el equipo.",
    adminDashboardCardLink: "Ir a Minor admin →",
    adminHoursDashboardCard:     "Horas Minor",
    adminHoursDashboardCardDesc: "Revisa el resumen semanal de horas imputadas por el equipo.",
    adminHoursDashboardCardLink: "Ver horas →",
    adminMonthlyDashboardCard:     "Resumen mensual Minor",
    adminMonthlyDashboardCardDesc: "Consulta horas agregadas por subproyecto y mes para todo el equipo.",
    adminMonthlyDashboardCardLink: "Ver resumen mensual →",
  },

  // ── Pricing ───────────────────────────────────────────────
  pricing: {
    pageTitle:              "Pricing de Oportunidades",
    pageSubtitle:           "Gestiona el pricing de las oportunidades de negocio.",
    newButton:              "Nueva oportunidad",
    newTitle:               "Nueva oportunidad",
    newSubtitle:            "Define los datos de la oportunidad y asigna empleados con su dedicación semanal.",
    editTitle:              "Editar oportunidad",
    editSubtitle:           "Modifica los datos de la oportunidad y la dedicación del equipo.",

    // Form fields
    fieldClient:            "Cliente",
    fieldClientPlaceholder: "Nombre del cliente",
    fieldName:              "Nombre de la oportunidad",
    fieldNamePlaceholder:   "Nombre descriptivo de la oportunidad",
    fieldDescription:       "Descripción",
    fieldDescriptionPlaceholder: "Descripción o notas adicionales",
    fieldMargin:            "Margen (%)",
    fieldMarginPlaceholder: "0",
    fieldStartDate:         "Fecha de inicio",
    fieldEndDate:           "Fecha de fin",

    // Employees section
    employeesTitle:         "Equipo",
    addEmployeeButton:      "Añadir empleado",
    noEmployees:            "No hay empleados asignados. Añade al menos uno.",
    colEmployee:            "Empleado",
    colCostPerHour:         "Coste/h (€)",
    colRevenuePerHour:      "Revenue/h (€)",
    colTotalHours:          "Total h",
    colTotalCost:           "Coste total (€)",
    colNsr:                 "NSR (€)",
    removeEmployee:         "Eliminar",

    // Totals
    summaryTotalHours:      "Horas totales del proyecto",
    summaryTotalCost:       "Coste total",
    summaryRevenue:         "Revenue (con margen)",
    summaryTarifa:          "Tarifa media (€/h)",
    summaryHoursSocio:      "Horas Socio",
    summaryHoursManager:    "Horas Manager",
    summaryHoursSenior:     "Horas Senior",
    summaryHoursStaff:      "Horas Staff",

    // Warnings
    warnNoSocio:            "No hay ningún Socio en la oportunidad.",
    warnSocioHours:         (actual: number, expected: number) =>
                              `Las horas del Socio son ${actual}h pero deberían ser el 1,5% del total (${expected}h).`,
    warnNoManager:          "No hay ningún Manager o Senior Manager en la oportunidad.",
    warnManagerHours:       (actual: number, expected: number) =>
                              `Las horas de los Managers son ${actual}h pero deberían ser el 10% del total (${expected}h).`,

    // Actions
    saveButton:             "Guardar oportunidad",
    savingButton:           "Guardando...",
    deleteButton:           "Eliminar",
    deleteConfirm:          "¿Eliminar esta oportunidad? Esta acción no se puede deshacer.",
    duplicateButton:        "Duplicar",

    // List
    colClient:              "Cliente",
    colProject:             "Cliente",
    colDates:               "Fechas",
    colMargin:              "Margen",
    colTeamSize:            "Equipo",
    colActions:             "Acciones",
    noOpportunities:        "No hay oportunidades creadas todavía.",
    dash:                   "—",

    // Errors
    errorLoading:           (msg: string) => `Error cargando oportunidades: ${msg}`,
    errorSaving:            (msg: string) => `Error guardando: ${msg}`,
    errorDeleting:          (msg: string) => `Error eliminando: ${msg}`,

    // Dashboard card
    dashboardCard:          "Pricing",
    dashboardCardDesc:      "Gestiona el pricing de oportunidades de negocio y asigna equipos.",
    dashboardCardLink:      "Ir a Pricing →",
  },

  // ── Notifications ────────────────────────────────────────
  notifications: {
    // Header bell
    bellLabel:              "Notificaciones",
    bellEmpty:              "No tienes notificaciones.",
    markAllRead:            "Marcar todo como leído",
    viewAll:                "Ver todas",
    unreadCount:            (n: number) => `${n} notificación${n !== 1 ? "es" : ""} sin leer`,

    // Admin page
    adminPageTitle:         "Gestión de notificaciones",
    adminPageSubtitle:      "Crea, edita y gestiona las notificaciones para los empleados.",
    newButton:              "Nueva notificación",
    newTitle:               "Crear notificación",
    newSubtitle:            "Envía una notificación a todos, a un proyecto o a una persona concreta.",
    editTitle:              "Editar notificación",
    editSubtitle:           "Modifica los datos de la notificación.",

    // Form fields
    titleLabel:             "Título",
    titlePlaceholder:       "Ej. Recordatorio de vacaciones",
    messageLabel:           "Mensaje",
    messagePlaceholder:     "Escribe el contenido de la notificación…",
    targetTypeLabel:        "Destinatario",
    targetTypeAll:          "Todos los empleados",
    targetTypeProject:      "Cliente específico",
    targetTypeEmployee:     "Empleado específico",
    targetProjectLabel:     "Seleccionar cliente",
    targetProjectPlaceholder: "Buscar cliente…",
    targetEmployeeLabel:    "Seleccionar empleado",
    targetEmployeePlaceholder: "Buscar empleado…",
    recurrenceLabel:        "Recurrencia",
    recurrenceNone:         "Una vez",
    recurrenceDaily:        "Diaria",
    recurrenceWeekly:       "Semanal",
    recurrenceMonthly:      "Mensual",
    submitCreate:           "Crear notificación",
    submitCreating:         "Creando…",
    submitUpdate:           "Guardar cambios",
    submitUpdating:         "Guardando…",
    successCreated:         "Notificación creada correctamente.",
    successUpdated:         "Notificación actualizada correctamente.",
    successDeleted:         "Notificación eliminada.",
    successCopied:          "Notificación duplicada.",

    // Table
    colTitle:               "Título",
    colMessage:             "Mensaje",
    colTarget:              "Destinatario",
    colRecurrence:          "Recurrencia",
    colStatus:              "Estado",
    colCreatedBy:           "Creada por",
    colCreatedAt:           "Fecha",
    colActions:             "Acciones",
    badgeActive:            "Activa",
    badgeInactive:          "Inactiva",
    badgeRecurrence:        (r: string) => r === 'none' ? 'Una vez' : r === 'daily' ? 'Diaria' : r === 'weekly' ? 'Semanal' : 'Mensual',
    targetAll:              "Todos",
    targetProject:          (name: string) => `Cliente: ${name}`,
    targetEmployee:         (name: string) => `Empleado: ${name}`,
    empty:                  "No hay notificaciones creadas.",
    confirmDelete:          "¿Eliminar esta notificación? Esta acción no se puede deshacer.",
    confirmCopy:            "¿Duplicar esta notificación?",

    // Actions
    editButton:             "Editar",
    deleteButton:           "Eliminar",
    copyButton:             "Duplicar",
    activateButton:         "Activar",
    deactivateButton:       "Desactivar",
    sending:                "Enviando…",
    sent:                   "Enviada",

    // Dashboard card
    dashboardCard:          "Notificaciones",
    dashboardCardDesc:      "Gestiona las notificaciones internas para los empleados.",
    dashboardCardLink:      "Ir a Notificaciones →",
  },

  // ── Imputaciones (Engagements & Assignments) ──────────────
  imputaciones: {
    // engagements section
    engagementsTitle:       "Engagements",
    engagementsSubtitle:   "Gestiona los engagements de cada cliente.",
    newEngagementButton:   "Nuevo engagement",
    editEngagementTitle:   "Editar engagement",
    newEngagementTitle:    "Nuevo engagement",
    engagementNameLabel:   "Nombre del engagement",
    engagementNamePlaceholder: "Ej. Desarrollo Frontend",
    engagementCodeLabel:   "Código",
    engagementCodePlaceholder: "Ej. ENG-001",
    engagementClientLabel: "Cliente",
    engagementStartDate:   "Fecha de inicio",
    engagementEndDate:     "Fecha de fin",
    engagementTotalAmount: "Importe total",
    engagementEstimatedExpenses: "Gastos previstos",
    engagementSaveButton:  "Guardar",
    engagementSavingButton: "Guardando...",
    engagementDeleteButton: "Eliminar",
    engagementDeleteConfirm: "¿Eliminar este engagement? Las asignaciones asociadas también se eliminarán.",
    engagementEmpty:       "No hay engagements para este cliente.",
    engagementColName:     "Nombre",
    engagementColCode:     "Código",
    engagementColClient:   "Cliente",
    engagementColStart:    "Inicio",
    engagementColEnd:      "Fin",
    engagementColTotalAmount: "Importe total",
    engagementColExpenses: "Gastos previstos",
    engagementColActions:  "Acciones",
    engagementSaved:       "Engagement guardado correctamente.",
    engagementDeleted:     "Engagement eliminado.",
    engagementError:       (msg: string) => `Error: ${msg}`,

    // imputaciones (assignments) section
    imputacionesTitle:     "Imputaciones",
    imputacionesSubtitle:  "Gestiona engagements y asigna horas semanales por empleado y cliente.",
    employeesTitle:        "Empleados del cliente",
    employeesEmpty:        "No hay empleados asignados a este cliente.",
    newImputacionButton:   "Añadir engagement",
    editImputacionTitle:   "Editar imputación",
    newImputacionTitle:    "Nueva imputación",
    imputacionEmployeeLabel: "Empleado",
    imputacionEmployeePlaceholder: "Buscar empleado...",
    imputacionEngagementLabel: "Engagement",
    imputacionEngagementPlaceholder: "Seleccionar engagement...",
    imputacionStartDate:   "Fecha de inicio",
    imputacionEndDate:     "Fecha de fin",
    imputacionWeeklyHours: "Horas semanales",
    imputacionWeeklyHoursHint: "Número de horas que el empleado debe imputar semanalmente a este engagement.",
    imputacionSaveButton:  "Guardar",
    imputacionSavingButton: "Guardando...",
    imputacionDeleteButton: "Eliminar",
    imputacionDeleteConfirm: "¿Eliminar esta imputación?",
    imputacionEmpty:       "No hay imputaciones para este cliente.",
    imputacionColEmployee: "Empleado",
    imputacionColEngagement: "Engagement",
    imputacionColStart:    "Inicio",
    imputacionColEnd:      "Fin",
    imputacionColHours:    "Horas/sem",
    imputacionColActions:  "Acciones",
    imputacionSaved:       "Imputación guardada correctamente.",
    imputacionDeleted:     "Imputación eliminada.",
    imputacionError:       (msg: string) => `Error: ${msg}`,
    imputacionTotalHours:  (n: number) => `Total: ${n}h/sem`,

    // Engagement-first flow
    selectEngagementTitle: "Selecciona un engagement",
    assignEmployeesTitle:  "Asignar empleados a",
    assignEmployeesHint:  "Pulsa + junto a un empleado para añadirlo al engagement. Después pulsa \"Finalizar\" para configurar las horas.",
    finalizeButton:        "Finalizar",
    addEmployeeToEngagement: "Añadir empleado al engagement",
    sortByCategory:        "Ordenar por categoría",
    sortByName:            "Ordenar por nombre",
    filterByCategory:      "Filtrar por categoría",
    allCategories:         "Todas",
    categoryStaff:         "Staff",
    categorySenior:        "Senior",
    categoryManager:       "Manager",
    categorySeniorManager: "Senior Manager",
    categoryExterno:       "Externo",
    categorySocio:         "Socio",
    categoryIntern:        "Becario",

    // Calendar view
    calendarSaveSuccess:  "Imputaciones guardadas correctamente.",
    calendarNoEmployees:  "No hay empleados asignados a este engagement.",
    calendarNoDates:      "El engagement no tiene fechas de inicio y fin definidas.",
    calendarColEmployee:  "Empleado",
    calendarColTotal:     "Total",
    regularLabel:         "Regular",
    summerLabel:          "Verano",
    holidayTooltip:       "Festivo",
    vacationDayCount:     (n: number) => `${n} día(s) de vacaciones`,
    baseHoursLabel:       "Horas base/semana",
    baseHoursPlaceholder: "Base",
    copyToAllWeeks:       "Copiar a todas las semanas",
    copyHoursFrom:        "Copiar horas de...",
    copyHoursTo:          "Copiar horas a...",
    copyHoursButton:      "Copiar",
    clearPastWeeks:       "Borrar semanas pasadas",
    clearPastWeeksConfirm:"¿Borrar las horas de todas las semanas anteriores a la semana en curso?",
    hidePastWeeks:        "Ocultar semanas pasadas",
    showAllWeeks:         "Mostrar todas",
    deletePast:           "Borrar pasado",
    showRemaining:        "Horas por asignar",
    hideRemaining:        "Ocultar horas por asignar",
    saveWarningTitle:     (n: number) => `${n} empleado(s) con horas sin completar`,
    fixButton:            "Corregir",
    weekLabel:            "Semana",
    remaining:            "pendiente",
    breakdownTitle:       "Desglose semanal",
    expectedLabel:        "Horas esperadas",
    thisEngagementLabel:  "Este engagement",
    holidaysLabel:        "Festivos",
    vacationsLabel:       "Vacaciones",
    remainingLabel:       "Pendiente",

    // Client filter
    clientFilterLabel:     "Cliente:",
    clientFilterAll:       "Todos los clientes",
    clientSelectPlaceholder: "Seleccionar cliente...",

    // Dashboard card
    dashboardCard:         "Imputaciones",
    dashboardCardDesc:     "Gestiona engagements y asigna horas semanales por empleado y cliente.",
    dashboardCardLink:     "Ir a Imputaciones →",

    // Dashboard weekly summary
    weeklyTitle:           "Imputaciones de la semana",
    thisWeekLabel:         "Esta semana",
    nextWeekLabel:         "Próxima semana",
    totalLabel:            "Total",
    noHoursThisWeek:       "Sin horas asignadas.",
    noEngagementMessage:   "No tienes engagement asociado, habla con tu manager para que te asigne uno.",
  },

} as const;
